/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author jhonatan
 */
public class TelaImagemView extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaImagemView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        btnFechar = new javax.swing.JButton();
        btnRestaurar = new javax.swing.JButton();
        btnDesfazer = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        lblImagem = new javax.swing.JLabel();
        chkAzul = new javax.swing.JCheckBox();
        chkVerde = new javax.swing.JCheckBox();
        chkVermelho = new javax.swing.JCheckBox();
        chkEspelhada = new javax.swing.JCheckBox();
        chkNegativa = new javax.swing.JCheckBox();
        chkSépia = new javax.swing.JCheckBox();
        chkPixelar = new javax.swing.JCheckBox();
        chkCinza = new javax.swing.JCheckBox();
        chkBrilho = new javax.swing.JCheckBox();
        chkRotacionar = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnFechar.setText("Fechar");

        btnRestaurar.setText("Restaurar padrão");

        btnDesfazer.setText("Desfazer");

        btnSalvar.setText("Salvar como");

        lblImagem.setMaximumSize(new java.awt.Dimension(535, 445));

        chkAzul.setText("Imagem Azul");

        chkVerde.setText("Imagem Verde");

        chkVermelho.setText("Imagem Vermelha");

        chkEspelhada.setText("Imagem Espelhada");

        chkNegativa.setText("Imagem Negativa");

        chkSépia.setText("Aplicar Cor Sépia");

        chkPixelar.setText("Pixelar Imagem");

        chkCinza.setText("Tons de cinza");

        chkBrilho.setText("Aplicar Brilho");

        chkRotacionar.setText("Rotacionar Imagem");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(391, Short.MAX_VALUE)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDesfazer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRestaurar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFechar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkAzul)
                            .addComponent(chkVerde)
                            .addComponent(chkVermelho)
                            .addComponent(chkEspelhada)
                            .addComponent(chkNegativa)
                            .addComponent(chkSépia)
                            .addComponent(chkPixelar)
                            .addComponent(chkCinza)
                            .addComponent(chkBrilho)
                            .addComponent(chkRotacionar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(chkAzul)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkVerde)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkVermelho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkEspelhada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkNegativa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkSépia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkPixelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkCinza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkBrilho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkRotacionar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnRestaurar)
                    .addComponent(btnDesfazer)
                    .addComponent(btnSalvar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaImagemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaImagemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaImagemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaImagemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaImagemView().setVisible(true);
            }
        });
    }

    public JButton getBtnDesfazer() {
        return btnDesfazer;
    }

    public JButton getBtnFechar() {
        return btnFechar;
    }

    public JButton getBtnRestaurar() {
        return btnRestaurar;
    }

    public JButton getBtnSalvar() {
        return btnSalvar;
    }

    public JFileChooser getFileChooser() {
        return fileChooser;
    }

    public JLabel getLblImagem() {
        return lblImagem;
    }

    public JCheckBox getChkAzul() {
        return chkAzul;
    }

    public JCheckBox getChkBrilho() {
        return chkBrilho;
    }

    public JCheckBox getChkCinza() {
        return chkCinza;
    }

    public JCheckBox getChkEspelhada() {
        return chkEspelhada;
    }

    public JCheckBox getChkNegativa() {
        return chkNegativa;
    }

    public JCheckBox getChkPixelar() {
        return chkPixelar;
    }

    public JCheckBox getChkRotacionar() {
        return chkRotacionar;
    }

    public JCheckBox getChkSépia() {
        return chkSépia;
    }

    public JCheckBox getChkVerde() {
        return chkVerde;
    }

    public JCheckBox getChkVermelho() {
        return chkVermelho;
    }



    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesfazer;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox chkAzul;
    private javax.swing.JCheckBox chkBrilho;
    private javax.swing.JCheckBox chkCinza;
    private javax.swing.JCheckBox chkEspelhada;
    private javax.swing.JCheckBox chkNegativa;
    private javax.swing.JCheckBox chkPixelar;
    private javax.swing.JCheckBox chkRotacionar;
    private javax.swing.JCheckBox chkSépia;
    private javax.swing.JCheckBox chkVerde;
    private javax.swing.JCheckBox chkVermelho;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel lblImagem;
    // End of variables declaration//GEN-END:variables
}
